name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  SUPABASE_JWT: ${{ secrets.SUPABASE_JWT }}
  PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
  HASH_KEY: ${{ secrets.HASH_KEY }}
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm ci

      - name: Build UI
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm run build
        
      - name: Start UI
        run: npm run preview &

      - name: Wait for UI to start
        run: sleep 10
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb
      
      - name: Run Playwright tests
        run: |
          Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox &
          npx playwright test
        env:
          DISPLAY: :0.0

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
