name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  SUPABASE_JWT: ${{ secrets.SUPABASE_JWT }}
  PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
  HASH_KEY: ${{ secrets.HASH_KEY }}
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.34.3-jammy

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clean cache
        run: sudo npm cache clean --force 

      - name: Install dependencies
        run: sudo npm ci

      - name: Build UI
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          sudo npm run build
        
      - name: Start UI
        run: sudo npm run preview &

      - name: Wait for UI to start
        run: sleep 10
      
      - name: Run Playwright tests
        run: sudo xvfb-run npm run test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
